trigger:
  branches:
    include:
      - main  # Replace with the branch you want to trigger the pipeline from (e.g., 'main')

pool:
  vmImage: 'Default'

variables:
  imageName: 'mudassir2222/automation_cockpit23may2024'  # Your Docker Hub repository and image name
  tag: 'latest'  # You can also add dynamic versioning if needed

steps:
# Step 1: Checkout the code from GitHub
- task: Checkout@1
  displayName: 'Checkout code'

# Step 2: Set up Maven and Build the Project
- task: UseMaven@3
  inputs:
    mavenVersionOption: 'Default'  # Use the default Maven version from the hosted agent
    pomFile: 'pom.xml'
    goals: 'clean install -DskipTests'  # Build the Maven project (skip tests to speed up the build)
  displayName: 'Build Maven Project'

# # Step 3: Build the Docker Image
# - task: Docker@2
#   inputs:
#     command: 'buildAndPush'
#     containerRegistry: 'DockerHubConnection'  # The name of the Docker Hub service connection created earlier
#     repository: $(imageName)
#     dockerfile: '$(Build.SourcesDirectory)/Dockerfile'  # Path to the Dockerfile
#     buildContext: '$(Build.SourcesDirectory)'  # Directory to use as build context
#     tags: |
#       $(tag)  # Tag the image with 'latest'
#   displayName: 'Build and Push Docker Image'

