trigger:
  branches:
    include:
      - main  # Adjust this to the branch you want to trigger the pipeline for (e.g., 'main')

pool:
  vmImage: 'ubuntu-latest'  # Using the latest Ubuntu image for the pipeline

variables:
  imageName: 'mudassir2222/automation_cockpit23may2024'  # Your Docker Hub repository and image name
  tag: 'latest'  # Tag the Docker image

steps:
# Step 1: Checkout the code from GitHub
- task: Checkout@1
  displayName: 'Checkout code'

# Step 2: Build the Maven project
- task: CommandLine@2
  inputs:
    script: |
      mvn clean install -DskipTests  # Build the Maven project, skipping tests for speed
  displayName: 'Build Maven Project'

# Step 3: Build the Docker Image
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    containerRegistry: 'DockerHubConnection'  # Name of the Docker Hub connection you set up earlier
    repository: $(imageName)  # The Docker Hub repository (mudassir2222/automation_cockpit23may2024)
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'  # Path to the Dockerfile
    buildContext: '$(Build.SourcesDirectory)'  # Context for the Docker build (root of the repository)
    tags: |
      $(tag)  # Use the 'latest' tag (or any dynamic tag you want)
  displayName: 'Build and Push Docker Image'

